#!/usr/bin/env python3

import argparse
import os
import sys
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument("--port", type=int, default=6020)
args = parser.parse_args()

arch = subprocess.run(
    ["go", "env", "GOARCH"], capture_output=True, text=True
).stdout.strip()

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(here)

subprocess.run(
    [
        "docker",
        "run",
        "-ti",
        "--rm",
        "--platform",
        f"linux/{arch}",
        "-v",
        f"{root}:/src",
        "-p",
        f"{args.port}:8080",
        "-w",
        "/src",
        "kellegous/build:751a8adc",
        "/bin/bash",
        "/src/etc/setup-dev.sh",
    ],
    check=True,
)
